In [1]:
# Imports as always...
import numpy as np
import matplotlib.pyplot as plt

from sqif import CVP, solve_cvp

# Ignore warnings.
import warnings
warnings.filterwarnings('ignore')

# Beautification.
plt.style.use('ggplot')

In [2]:
# Instantiate an empty CVP object.
cvp = CVP()

Let's use our implementation to experiment with reproducing the findings in Yan et al. (2023) -- the CVP part, that is/

### 3-qubits

The 11-bit integer $N=1997$ is claimed to be effectively solvable in 3 qubits.

In [30]:
# Setting up the 3-qubit problem.
cvp.generate_cvp(N=1961, l=1, c=1.5, seed=42)

print(f'B = \n{cvp.B}\n')
print(f't = \n{cvp.t}\n')

# Solve the 3-qubit CVP.
lattice_vectors, outcome_probabilities, b_op = solve_cvp(
    cvp, n_samples=1000, delta=.75, p=2, min_method='Nelder-Mead', verbose=False
)

# Results of the SQIF algorithm.
for vec, prob in zip(lattice_vectors, outcome_probabilities):
    # Compute distance to the target vector.
    dist = np.linalg.norm(cvp.t - vec)

    if np.all(vec == b_op):
        extra = ' [Approximate Solution]'
    else:
        extra = ''

    print(f'{vec} with prob {round(prob, 3):.3f}; distance to t: {round(dist, 3):.3f}{extra}')

B = 
[  1  0  0 ]
[  0  1  0 ]
[  0  0  2 ]
[ 22 35 51 ]

t = 
(0, 0, 0, 240)

[  3   2   4 238] with prob 0.453; distance to t: 5.745
[  3   5   0 241] with prob 0.362; distance to t: 5.916
[  0   4   4 242] with prob 0.137; distance to t: 6.000 [Approximate Solution]


### 5 qubits

The 26-bit integer $N=48567227$ is claimed to be effectively solvable in 5 qubits.

In [24]:
# Setting up the 5-qubit problem.
cvp.generate_cvp(N=48567227, l=1, c=4, seed=42)

print(f'B = \n{cvp.B}\n')
print(f't = \n{cvp.t}\n')

# Solve the 5-qubit CVP.
lattice_vectors, outcome_probabilities, b_op = solve_cvp(
    cvp, n_samples=1000, delta=.75, p=2, min_method='Nelder-Mead', verbose=False
)

# Results of the SQIF algorithm.
for vec, prob in zip(lattice_vectors, outcome_probabilities):
    # Compute distance to the target vector.
    dist = np.linalg.norm(cvp.t - vec)

    if np.all(vec == b_op):
        extra = ' [Approximate Solution]'
    else:
        extra = ''

    print(f'{vec} with prob {round(prob, 3):.3f}; distance to t: {round(dist, 3):.3f}{extra}')

B = 
[    1     0     0     0     0 ]
[    0     3     0     0     0 ]
[    0     0     2     0     0 ]
[    0     0     0     1     0 ]
[    0     0     0     0     2 ]
[ 6931 10986 16094 19459 23979 ]

t = 
(0, 0, 0, 0, 0, 176985)

[    -6      0      0     10      2 176983] with prob 0.581; distance to t: 12.000 [Approximate Solution]
[     8     -3     -4      6      4 176986] with prob 0.163; distance to t: 11.916
[    -1      3      4      6      2 176976] with prob 0.106; distance to t: 12.124
[    -8      6      4      3     10 176984] with prob 0.053; distance to t: 15.033


### 10 qubits

The 48-bit integer $N=261980999226229$ is claimed to be effectively solvable in 10 qubits.

In [23]:
# Setting up the 10-qubit problem.
cvp.generate_cvp(N=261980999226229, l=1, c=4, seed=42)

print(f'B = \n{cvp.B}\n')
print(f't = \n{cvp.t}\n')

# Solve the 10-qubit CVP.
lattice_vectors, outcome_probabilities, b_op = solve_cvp(
    cvp, n_samples=1000, delta=.75, p=2, min_method='Nelder-Mead', verbose=False
)

# Results of the SQIF algorithm.
for vec, prob in zip(lattice_vectors, outcome_probabilities):
    # Compute distance to the target vector.
    dist = np.linalg.norm(cvp.t - vec)

    if np.all(vec == b_op):
        extra = ' [Approximate Solution]'
    else:
        extra = ''

    print(f'{vec} with prob {round(prob, 3):.3f}; distance to t: {round(dist, 3):.3f}{extra}')

B = 
[    1     0     0     0     0     0     0     0 ]
[    0     3     0     0     0     0     0     0 ]
[    0     0     1     0     0     0     0     0 ]
[    0     0     0     4     0     0     0     0 ]
[    0     0     0     0     2     0     0     0 ]
[    0     0     0     0     0     3     0     0 ]
[    0     0     0     0     0     0     2     0 ]
[    0     0     0     0     0     0     0     4 ]
[ 6931 10986 16094 19459 23979 25649 28332 29444 ]

t = 
(0, 0, 0, 0, 0, 0, 0, 0, 331993)

[     3      3      4      4      4      3      8      4 331993] with prob 0.091; distance to t: 12.450 [Approximate Solution]
[     3     -3      9      8      2      0      6      4 331990] with prob 0.061; distance to t: 15.100
[     0      3     12      4      4     -3      4      4 331990] with prob 0.054; distance to t: 15.330
[    -4     -3      9      8      4      3      8      0 331989] with prob 0.047; distance to t: 16.583
[    -3     -3      7      4     10      3      4      4 